### PR TITLE
prepare release

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Review by rafaqz — APPROVED** [review]
1.0! 

Sure we don't need to break anthing?

**Comment by SimonDanisch** [comment]
>Sure we don't need to break anything?

Well, I dont plan to break much in the API ;) 
And if we do, we can always tag 2.0 🤷 I tried to be less hesitant with going for 1.0 for new repos, since otherwise semver doesn't really work.

**Review by visr — COMMENTED** [review]
Agree on calling it 1.0, but perhaps it's good to consider #23.

**Comment by yeesian** [comment]
If there's consensus, we can close this in lieu of #23?

**Comment by visr** [comment]
part of #23

**Pull request closed without merging**
