### PR TITLE
Add GFT.val definitions for the CRS defined here

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by rafaqz** [comment]
Why are these not just const aliases for `EPSG(x)`?

**Comment by asinghvi17** [comment]
You can't dispatch on the int within an EPSG I think

**Comment by rafaqz** [comment]
Right. I guess I'm a little worried that `convert` to other projections wont work anywhere in the ecosystem currently.

I think we need to define `convert` methods on these objects and then make them call `convert` again on the `EPSG` or just return the `EPSG` object if that's the target.

**Comment by asinghvi17** [comment]
All projections can be said to have a "canonical form" which is basically what Proj accepts, so in that case maybe we add a GFT method `canonical` or something, that guarantees it returns a Proj-compatible String?

**Comment by rafaqz** [comment]
Ok maybe I need to explain a little more...

Most of the purpose of GFT as a package is that various geospatial data formats only allow using a specific kind of string/number (Proj/wellknowntext/epsg/etc) and by wrapping a known string or number in a wrapper every package knows exactly what the thing is without parsing it, and is e.g. allowed to write the contents to a file.

We need a `convert` method so that packages can convert to the format that they specifically need.

My issue is not about Proj compatability _at all_ because proj has automatic detection. Its about all the other packages that don't depend on a binary like proj/gdal being able to either know a CRS is already in the right format for them, or have an external package they don't depend on do the conversion by pirating `convert` for GFT and telling users to load it by default.

Currently ArchGDAL is the anointed external package that does that because historically most packages that needed this depended on ArchGDAL already, but it could also just be Proj.

But `Base.convert` is the _key_ method in GFT, and it not working makes something being `<: GFT` not worth very much.

**Comment by asinghvi17** [comment]
Makes sense - and that should definitely go in the GFT docs!  I don't mind implementing converts for these particular CRSs here, but we should then probably abstract this out to a separate package at some stage...

**Comment by rafaqz** [comment]
> and that should definitely go in the GFT docs! 

Absolutely, I haven't been the best communicator with all these things

> but we should then probably abstract this out to a separate package at some stage

It could also just go in GFT.jl under an e.g. `ExplicitCoordinateReferenceSystem` abstract type or something? and we could have a list of common things like these two? I don't know, I never really understood how this should work, maybe also why the documentation is bad - the idea was pretty vague.

**Comment by asinghvi17** [comment]
That would work too - maybe you can have a `to_conventional` function that all GFT convert methods can call?

**Comment by rafaqz** [comment]
What would `to_conventional` do?

**Comment by asinghvi17** [comment]
A translation to any native GFT type so that convert can just call that

**Comment by rafaqz** [comment]
Arent they all one-liners too ? ;)

**Comment by asinghvi17** [comment]
Well you'd have to define a convert for each separate type (EPSG, ProjJSON, ProjString, EsriWKT, KML, ...) but with a conventional/canonical form, you don't have to do that

**Comment by rafaqz** [comment]
Sorry I don't get it... my reason to define the exact conversion is to skip needing Proj/ArchGDAL for any conversion at all, and just make them instant. The canonical version still needs those for most conversions.

**Comment by asinghvi17** [comment]
I'm not saying that we should define only the canonical conversion, just that this fallback should exist (I probably wouldn't end up implementing an explicit KML method, for example, and it could be useful for that to have an automatic fallback).

**Comment by rafaqz** [comment]
Makes sense

**Pull request merged**
