### PR TITLE
remove HTTP, ImageMagick and TileProviders deps

### PR DESCRIPTION
**Pull request by visr**
This is on top of #22.

I'm wondering if it's worth tying ourselves to HTTP, ImageMagick and TileProviders for 3 lines of code:

```julia
function get_tile(provider::AbstractProvider, tile::Tile)
    url = geturl(provider, tile.x, tile.y, tile.z)
    result = HTTP.get(url)
    ImageMagick.readblob(result.body)
end
```

I think maybe it makes more sense for this function to live in [Tyler](https://github.com/MakieOrg/Tyler.jl), and then other users of this package are free to do it in another way without needing these dependencies.

tile0

### CODE REVIEW

**Comment by rafaqz** [comment]
Isn't TileProviders.jl is used in more places than that?

**Comment by SimonDanisch** [comment]
Sounds fair, I was thinking the same at some point ;)

**Comment by SimonDanisch** [comment]
Tyler actually already has its own implementation, since the exposed `fetchtile` method wasn't customizable enough!

**Comment by SimonDanisch** [comment]
I guess we also need to further update the README!

**Comment by visr** [comment]
I just updated the README in 47309c6a8070972816fd7cbaaae2291155fe09bf, it now looks like this:
https://github.com/JuliaGeo/MapTiles.jl/blob/stripdeps/README.md

CI for 1.6 fails because TileProviders doesn't support it yet, I'll look into that.

**Comment by visr** [comment]
With TileProviders 0.1.1 this is now also passing on julia 1.6. Shall we merge and get the registration process going?

**Review by SimonDanisch — APPROVED** [review]

**Pull request merged**
